import { IEmailProvider, EmailOptions } from './email-provider.interface.ts';
import { ConsoleEmailProvider } from './console-provider.ts';
import { SmtpEmailProvider } from './smtp-provider.ts';
import { ResendEmailProvider } from './resend-provider.ts';
import { NotificationType, RiskRating } from '../../../../shared/types.ts';
import { emailDeduplication } from '../../../../shared/risk-scoring.ts';

export class EmailService {
  private provider: IEmailProvider;

  constructor() {
    const providerType = (process.env.EMAIL_PROVIDER || 'console').toLowerCase();
    switch (providerType) {
      case 'smtp':
        this.provider = new SmtpEmailProvider();
        break;
      case 'resend':
        this.provider = new ResendEmailProvider();
        break;
      default:
        this.provider = new ConsoleEmailProvider();
        break;
    }
  }

  public setProvider(provider: IEmailProvider) {
    this.provider = provider;
  }

  public getProviderName(): string {
    return this.provider.name;
  }

  /**
   * Generates enterprise responsive HTML email template
   */
  private generateHtmlLayout(headerTitle: string, badgeText: string, badgeColor: string, contentHtml: string, actionUrl?: string, actionText?: string): string {
    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f4f6f9; color: #1e293b; }
    .container { max-width: 600px; margin: 24px auto; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05); }
    .header { background: #0f172a; color: #ffffff; padding: 24px; border-bottom: 3px solid #0284c7; }
    .header h1 { margin: 0; font-size: 18px; font-weight: 700; letter-spacing: 0.5px; }
    .header .subtitle { font-size: 12px; color: #94a3b8; margin-top: 4px; text-transform: uppercase; }
    .body { padding: 28px 24px; line-height: 1.6; }
    .badge { display: inline-block; padding: 4px 10px; border-radius: 4px; font-weight: 700; font-size: 12px; color: #ffffff; background: ${badgeColor}; text-transform: uppercase; margin-bottom: 16px; }
    .table-grid { width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 14px; }
    .table-grid td { padding: 10px 12px; border-bottom: 1px solid #f1f5f9; }
    .table-grid td.label { font-weight: 600; color: #64748b; width: 38%; }
    .table-grid td.val { font-weight: 500; color: #0f172a; }
    .btn { display: inline-block; padding: 12px 24px; background: #0284c7; color: #ffffff !important; text-decoration: none; border-radius: 6px; font-weight: 600; font-size: 14px; margin-top: 20px; }
    .footer { background: #f8fafc; padding: 16px 24px; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; text-align: center; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div class="subtitle">Enterprise Risk Management System</div>
      <h1>${headerTitle}</h1>
    </div>
    <div class="body">
      <div class="badge">${badgeText}</div>
      ${contentHtml}
      ${actionUrl ? `<div style="text-align: center; margin-top: 24px;"><a href="${actionUrl}" class="btn">${actionText || 'View Risk Assessment'}</a></div>` : ''}
    </div>
    <div class="footer">
      This is an automated notification generated by the Enterprise RCSA System. Please do not reply directly to this email.<br>
      Confidential & Proprietary © ${new Date().getFullYear()} Financial Services Group.
    </div>
  </div>
</body>
</html>
    `;
  }

  /**
   * Risk Input / Submission Alert Template (Rule 6, 7 & Section 17)
   */
  public createRiskSubmissionEmail(riskData: {
    riskId: string;
    riskEvent: string;
    unit: string;
    riskOwner: string;
    inherentLikelihood: number;
    inherentImpact: number;
    inherentScore: number;
    inherentRating: RiskRating;
    existingControlSummary?: string;
    residualScore: number;
    residualRating: RiskRating;
    actionPlanSummary?: string;
    targetDate?: string;
    baseUrl?: string;
  }): { subject: string; html: string } {
    const subject = `[RCSA ALERT] ${riskData.inherentRating} Risk – ${riskData.riskId}`;
    const badgeColor = riskData.inherentRating === 'EXTREME' ? '#ef4444' : riskData.inherentRating === 'HIGH' ? '#f97316' : '#f59e0b';
    const baseUrl = riskData.baseUrl || process.env.APP_URL || 'http://localhost:3000';
    const actionUrl = `${baseUrl}/#risks`;

    const contentHtml = `
      <p style="font-size: 15px; margin-top: 0;">
        A new risk assessment with rating <strong>${riskData.inherentRating}</strong> has been submitted and requires review.
      </p>

      <table class="table-grid">
        <tr><td class="label">Risk ID</td><td class="val"><strong>${riskData.riskId}</strong></td></tr>
        <tr><td class="label">Risk Event</td><td class="val">${riskData.riskEvent}</td></tr>
        <tr><td class="label">Work Unit</td><td class="val">${riskData.unit}</td></tr>
        <tr><td class="label">Risk Owner</td><td class="val">${riskData.riskOwner}</td></tr>
        <tr><td class="label">Inherent Score / Rating</td><td class="val"><strong>${riskData.inherentScore} (${riskData.inherentRating})</strong> [L:${riskData.inherentLikelihood} × I:${riskData.inherentImpact}]</td></tr>
        <tr><td class="label">Existing Controls</td><td class="val">${riskData.existingControlSummary || 'Controls Registered'}</td></tr>
        <tr><td class="label">Residual Score / Rating</td><td class="val"><strong>${riskData.residualScore} (${riskData.residualRating})</strong></td></tr>
        ${riskData.actionPlanSummary ? `<tr><td class="label">Action Plan</td><td class="val">${riskData.actionPlanSummary}</td></tr>` : ''}
        ${riskData.targetDate ? `<tr><td class="label">Target Date</td><td class="val">${new Date(riskData.targetDate).toLocaleDateString()}</td></tr>` : ''}
      </table>
    `;

    const html = this.generateHtmlLayout(
      'Risk Assessment Notification',
      `${riskData.inherentRating} Priority`,
      badgeColor,
      contentHtml,
      actionUrl,
      'View Risk Assessment'
    );

    return { subject, html };
  }

  /**
   * Action Plan Reminder / Overdue / Escalation Email (Sections 18 & 19)
   */
  public createActionPlanReminderEmail(planData: {
    riskId: string;
    riskEvent: string;
    actionPlan: string;
    picName: string;
    priority: string;
    targetDate: string;
    progress: number;
    notificationType: NotificationType;
    baseUrl?: string;
  }): { subject: string; html: string } {
    let subjectPrefix = '[RCSA REMINDER]';
    let badgeText = 'Reminder';
    let badgeColor = '#0284c7';

    switch (planData.notificationType) {
      case 'ACTION_PLAN_H7':
        subjectPrefix = '[RCSA REMINDER H-7]';
        badgeText = 'Due in 7 Days';
        badgeColor = '#0284c7';
        break;
      case 'ACTION_PLAN_H3':
        subjectPrefix = '[RCSA REMINDER H-3]';
        badgeText = 'Due in 3 Days';
        badgeColor = '#f59e0b';
        break;
      case 'ACTION_PLAN_H1':
        subjectPrefix = '[RCSA URGENT H-1]';
        badgeText = 'Due Tomorrow';
        badgeColor = '#f97316';
        break;
      case 'ACTION_PLAN_DUE':
        subjectPrefix = '[RCSA DUE TODAY]';
        badgeText = 'Due Today';
        badgeColor = '#ef4444';
        break;
      case 'ACTION_PLAN_OVERDUE':
        subjectPrefix = '[RCSA OVERDUE ALERT]';
        badgeText = 'Action Plan Overdue';
        badgeColor = '#b91c1c';
        break;
      case 'ESCALATION_7D':
        subjectPrefix = '[RCSA ESCALATION LEVEL 3]';
        badgeText = 'Escalation to Risk Management (Overdue >7d)';
        badgeColor = '#991b1b';
        break;
      case 'ESCALATION_14D':
        subjectPrefix = '[RCSA EXECUTIVE ESCALATION]';
        badgeText = 'Escalation to Management (Overdue >14d)';
        badgeColor = '#7f1d1d';
        break;
    }

    const subject = `${subjectPrefix} ${planData.riskId} – ${planData.actionPlan.substring(0, 40)}`;
    const baseUrl = planData.baseUrl || process.env.APP_URL || 'http://localhost:3000';
    const actionUrl = `${baseUrl}/#actions`;

    const contentHtml = `
      <p style="font-size: 15px; margin-top: 0;">
        This is an automated tracking notice regarding the mitigation action plan assigned for <strong>${planData.riskId}</strong>.
      </p>

      <table class="table-grid">
        <tr><td class="label">Risk ID</td><td class="val"><strong>${planData.riskId}</strong></td></tr>
        <tr><td class="label">Risk Event</td><td class="val">${planData.riskEvent}</td></tr>
        <tr><td class="label">Mitigation Plan</td><td class="val"><strong>${planData.actionPlan}</strong></td></tr>
        <tr><td class="label">PIC</td><td class="val">${planData.picName}</td></tr>
        <tr><td class="label">Priority</td><td class="val">${planData.priority}</td></tr>
        <tr><td class="label">Target Date</td><td class="val"><strong>${new Date(planData.targetDate).toLocaleDateString()}</strong></td></tr>
        <tr><td class="label">Current Progress</td><td class="val"><strong>${planData.progress}%</strong></td></tr>
      </table>
    `;

    const html = this.generateHtmlLayout(
      'Mitigation Action Plan Tracking',
      badgeText,
      badgeColor,
      contentHtml,
      actionUrl,
      'Update Mitigation Progress'
    );

    return { subject, html };
  }

  /**
   * Dispatches email via configured provider
   */
  public async send(options: EmailOptions) {
    return await this.provider.sendEmail(options);
  }
}

export const emailService = new EmailService();
